In [27]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import numba
import random


/home/jmmauricio/bin/anaconda3/lib/python3.5/site-packages/matplotlib/__init__.py:1041: UserWarning: Duplicate key in file "/home/jmmauricio/bin/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/presentation.mplstyle", line #10
  (fname, cnt))
/home/jmmauricio/bin/anaconda3/lib/python3.5/site-packages/matplotlib/__init__.py:1041: UserWarning: Duplicate key in file "/home/jmmauricio/bin/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/presentation.mplstyle", line #11
  (fname, cnt))
/home/jmmauricio/bin/anaconda3/lib/python3.5/site-packages/matplotlib/__init__.py:878: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))


In [18]:
P = np.array([[0.9, 0.1],[0.7, 0.3]])
S_0 = np.array([[0.2, 0.8]])
for it in range(10):
    S_0 = S_0 @ P
    print(S_0)

[[ 0.74  0.26]]
[[ 0.848  0.152]]
[[ 0.8696  0.1304]]
[[ 0.87392  0.12608]]
[[ 0.874784  0.125216]]
[[ 0.8749568  0.1250432]]
[[ 0.87499136  0.12500864]]
[[ 0.87499827  0.12500173]]
[[ 0.87499965  0.12500035]]
[[ 0.87499993  0.12500007]]


In [15]:
S_0 = S_0 @ P
S_0

array([[ 0.87499965,  0.12500035]])

In [17]:
P = np.array([[0.8, 0.2],[0.6, 0.4]])
S_0 = np.array([[0.1, 0.9]])
for it in range(10):
    S_0 = S_0 @ P
    print(S_0)

[[ 0.62  0.38]]
[[ 0.724  0.276]]
[[ 0.7448  0.2552]]
[[ 0.74896  0.25104]]
[[ 0.749792  0.250208]]
[[ 0.7499584  0.2500416]]
[[ 0.74999168  0.25000832]]
[[ 0.74999834  0.25000166]]
[[ 0.74999967  0.25000033]]
[[ 0.74999993  0.25000007]]


In [20]:
P = np.array([[0.8, 0.2],[0.6, 0.4]])
S_0 = np.array([[0.75, 0.25]])
S_0 = S_0 @ P
S_0

array([[ 0.75,  0.25]])

In [26]:
P**10000

array([[ 0.,  0.],
       [ 0.,  0.]])

In [39]:
P  = np.genfromtxt('markov_clearness.csv', delimiter=',')


In [41]:
P**200

array([[  0.00000000e+000,   0.00000000e+000,   0.00000000e+000, ...,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   6.68600633e-036,   3.08209983e-096, ...,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   3.87347466e-321,   4.03708001e-017, ...,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       ..., 
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000, ...,
          1.73727840e-121,   2.76690297e-179,   1.27552619e-153],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000, ...,
          1.30252552e-176,   7.76848203e-122,   1.62874255e-100],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000, ...,
          0.00000000e+000,   0.00000000e+000,   6.43099933e-009]])

In [35]:
df_ClearnessIndexTPM[1]

0      0.000000
1      0.000000
2      0.000000
3      0.000000
4      0.000000
5      0.000000
6      0.000000
7      0.000000
8      0.000000
9      0.000000
10     0.000000
11     0.000000
12     0.000000
13     0.000000
14     0.000000
15     0.000000
16     0.000000
17     0.000000
18     0.000000
19     0.000000
20     0.000000
21     0.000000
22     0.000000
23     0.000000
24     0.000000
25     0.000000
26     0.000000
27     0.000000
28     0.000000
29     0.000000
         ...   
71     0.002221
72     0.002974
73     0.004219
74     0.000000
75     0.003007
76     0.002209
77     0.004410
78     0.001783
79     0.002409
80     0.001378
81     0.001064
82     0.000656
83     0.001100
84     0.001533
85     0.003768
86     0.003339
87     0.006016
88     0.004169
89     0.004333
90     0.004507
91     0.005747
92     0.007709
93     0.012384
94     0.015184
95     0.022021
96     0.026621
97     0.074047
98     0.128276
99     0.247781
100    0.011828
Name: 1, dtype: float64