[Spectrum’s 2014 Ranking](http://spectrum.ieee.org/computing/software/top-10-programming-languages)

Para los cáculos se utilizará el módulo [numpy](http://www.numpy.org/)

Para poder utilizar funciones de numpy primero se las debe importar. Una manera de hacerlo es la siguiete:

In [1]:
from numpy import *

De esta manera se importaran todas las funciones y se podrán hacer cálculos como sigue:


In [2]:
sqrt(3.0)

1.7320508075688772

In [3]:
abs(2+1j*3)

3.605551275463989

Otra alternativa es importar la libreria numpy con un nombre, por ejemplo *np* de la siguiente manera:

In [4]:
import numpy as np

de esta manera los cálculos anteriores se harían de la siguiente manera:

In [5]:
np.sqrt(3.0)

1.7320508075688772

In [6]:
np.abs(2+1j*3)

3.6055512754639891

In [7]:
np.angle(2+1j*3)

0.98279372324732905

numpy también trabaja con vectores. El tipo de variable es un numpy.array y se puede definir de muchas maneras. A continuación se genera un vector a partir de una lista con números:

In [8]:
X = np.array([0.0,1.0,2.0,3.0,4.0])

In [9]:
X

array([ 0.,  1.,  2.,  3.,  4.])

Con los numpy.array se pueden hacer cálculos:

In [10]:
Y = X*2        # multiplicación

In [11]:
print(Y)

[ 0.  2.  4.  6.  8.]


In [12]:
Y = X**2        # potencia

In [13]:
print(Y)

[  0.   1.   4.   9.  16.]


funciones trigonométricas:

In [14]:
Z = np.sin(2.0*np.pi*X/10.0)

In [15]:
print(Z)

[ 0.          0.58778525  0.95105652  0.95105652  0.58778525]


Otra manera de crear numpy.array's es con linspace:

In [16]:
n = np.linspace(0.0,1500.0,10)   # linspace(start, stop, num=50, endpoint=True, retstep=False)

In [17]:
print(n)

[    0.           166.66666667   333.33333333   500.           666.66666667
   833.33333333  1000.          1166.66666667  1333.33333333  1500.        ]


## Advance

https://conference.scipy.org/scipy2010/slides/tutorials/stefan_vd_walt_numpy_advanced.pdf

In [20]:
a = np.arange(12).reshape((3,4))

In [21]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
b = np.array([1,2,3])[:,np.newaxis]

In [24]:
b

array([[1],
       [2],
       [3]])

In [25]:
a+b

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

### Structured arrays

In [67]:
dt = np.dtype([('Y_ii',np.float64),('max_iter',np.float64)])

In [73]:
R1 = np.random.random((4,4))
R2 = np.random.random((,))
params = np.rec.array([R,2],dtype=dt)

SyntaxError: invalid syntax (<ipython-input-73-58bb1b3f35b4>, line 2)

In [70]:
params.max_iter

array([[ 0.54464955,  0.01074485,  0.45675558,  0.43040398],
       [ 0.175311  ,  0.64428385,  0.29707789,  0.82781064],
       [ 0.95926218,  0.62165257,  0.6109098 ,  0.00472556],
       [ 0.35514452,  0.87655991,  0.24581001,  0.2819262 ]])

In [44]:
params = np.rec.array(np.zeros(3),dtype=dt)

In [45]:
params

rec.array([(0.0,), (0.0,), (0.0,)], 
          dtype=[('Y_ii', '<f8')])

In [46]:
dt_params = np.dtype([('Y_vv',np.float64),('Y_vi',np.float64),
                      ('Y_iv',np.float64),('Y_ii',np.float64),
                      ('inv_Y_ii',np.float64),
                      ('V_known',np.float64),('V_unknown',np.float64),
                      ('I_unknown',np.float64),('I_known',np.float64),
                      ('pq_3pn_int',np.int32),('pq_3pn',np.float64),
                      ('V_unknown_0',np.float64),
                      ('I_known_0',np.float64),
                      ('max_iter',np.int32)
                      ])

In [47]:
dt_params

dtype([('Y_vv', '<f8'), ('Y_vi', '<f8'), ('Y_iv', '<f8'), ('Y_ii', '<f8'), ('inv_Y_ii', '<f8'), ('V_known', '<f8'), ('V_unknown', '<f8'), ('I_unknown', '<f8'), ('I_known', '<f8'), ('pq_3pn_int', '<i4'), ('pq_3pn', '<f8'), ('V_unknown_0', '<f8'), ('I_known_0', '<f8'), ('max_iter', '<i4')])

In [53]:
A = np.rec.array([0]*14,dtype=dt_params)

In [54]:
A

rec.array((0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0, 0.0, 0.0, 0.0, 0), 
          dtype=[('Y_vv', '<f8'), ('Y_vi', '<f8'), ('Y_iv', '<f8'), ('Y_ii', '<f8'), ('inv_Y_ii', '<f8'), ('V_known', '<f8'), ('V_unknown', '<f8'), ('I_unknown', '<f8'), ('I_known', '<f8'), ('pq_3pn_int', '<i4'), ('pq_3pn', '<f8'), ('V_unknown_0', '<f8'), ('I_known_0', '<f8'), ('max_iter', '<i4')])

In [81]:
dt_params = np.dtype([('Y_vv',np.float64),
                      ('max_iter',np.int32)
                      ])

In [98]:
Y_vv = np.zeros((3,3))
Y_ii = np.zeros((3,3))

In [99]:
A = np.rec.array([(Y_vv),(Y_ii)], dtype = dt_params)

In [95]:
np.array([3])

array([3])

In [104]:
A.Y_vv = np.zeros((3,1))